# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_ui.ui'
#
# Created: Sat Jun  5 20:10:56 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 699)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_search = QtGui.QPushButton(self.frame)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.radioButton_neural_net = QtGui.QRadioButton(self.frame)
        self.radioButton_neural_net.setObjectName("radioButton_neural_net")
        self.horizontalLayout.addWidget(self.radioButton_neural_net)
        self.lineEdit_search = QtGui.QLineEdit(self.frame)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.tab_1)
        self.label.setTextFormat(QtCore.Qt.LogText)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tableView_entity = QtGui.QTableView(self.tab_1)
        self.tableView_entity.setObjectName("tableView_entity")
        self.verticalLayout_3.addWidget(self.tableView_entity)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_entity_browse_tags = QtGui.QLabel(self.tab_2)
        self.label_entity_browse_tags.setTextFormat(QtCore.Qt.LogText)
        self.label_entity_browse_tags.setObjectName("label_entity_browse_tags")
        self.verticalLayout_4.addWidget(self.label_entity_browse_tags)
        self.treeView_entity_browse_tags = QtGui.QTreeView(self.tab_2)
        self.treeView_entity_browse_tags.setObjectName("treeView_entity_browse_tags")
        self.verticalLayout_4.addWidget(self.treeView_entity_browse_tags)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setTextFormat(QtCore.Qt.LogText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.treeView_entity_browse = QtGui.QTreeView(self.tab_3)
        self.treeView_entity_browse.setObjectName("treeView_entity_browse")
        self.verticalLayout_5.addWidget(self.treeView_entity_browse)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_repo = QtGui.QMenu(self.menu_file)
        self.menu_repo.setObjectName("menu_repo")
        self.menu_users = QtGui.QMenu(self.menu_file)
        self.menu_users.setObjectName("menu_users")
        self.menu_objects = QtGui.QMenu(self.menubar)
        self.menu_objects.setObjectName("menu_objects")
        self.menu_add_entity = QtGui.QMenu(self.menu_objects)
        self.menu_add_entity.setObjectName("menu_add_entity")
        self.menu_mark = QtGui.QMenu(self.menu_objects)
        self.menu_mark.setObjectName("menu_mark")
        self.menu_metadata = QtGui.QMenu(self.menubar)
        self.menu_metadata.setObjectName("menu_metadata")
        self.menu = QtGui.QMenu(self.menu_metadata)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_create_repo = QtGui.QAction(MainWindow)
        self.action_create_repo.setObjectName("action_create_repo")
        self.action_open_repo = QtGui.QAction(MainWindow)
        self.action_open_repo.setObjectName("action_open_repo")
        self.action_delete_repo = QtGui.QAction(MainWindow)
        self.action_delete_repo.setObjectName("action_delete_repo")
        self.action_update_user = QtGui.QAction(MainWindow)
        self.action_update_user.setObjectName("action_update_user")
        self.action_delete_user_from_repo = QtGui.QAction(MainWindow)
        self.action_delete_user_from_repo.setObjectName("action_delete_user_from_repo")
        self.action_switch_user = QtGui.QAction(MainWindow)
        self.action_switch_user.setObjectName("action_switch_user")
        self.action_add_file = QtGui.QAction(MainWindow)
        self.action_add_file.setObjectName("action_add_file")
        self.action_add_URL = QtGui.QAction(MainWindow)
        self.action_add_URL.setObjectName("action_add_URL")
        self.action_mark_tag = QtGui.QAction(MainWindow)
        self.action_mark_tag.setObjectName("action_mark_tag")
        self.action_mark_field = QtGui.QAction(MainWindow)
        self.action_mark_field.setObjectName("action_mark_field")
        self.action_change_entity = QtGui.QAction(MainWindow)
        self.action_change_entity.setObjectName("action_change_entity")
        self.action_delete_entity = QtGui.QAction(MainWindow)
        self.action_delete_entity.setObjectName("action_delete_entity")
        self.action_search = QtGui.QAction(MainWindow)
        self.action_search.setObjectName("action_search")
        self.action_repo_files = QtGui.QAction(MainWindow)
        self.action_repo_files.setObjectName("action_repo_files")
        self.action_setting_tags = QtGui.QAction(MainWindow)
        self.action_setting_tags.setObjectName("action_setting_tags")
        self.action_setting_fields = QtGui.QAction(MainWindow)
        self.action_setting_fields.setObjectName("action_setting_fields")
        self.menu_repo.addAction(self.action_create_repo)
        self.menu_repo.addAction(self.action_open_repo)
        self.menu_repo.addAction(self.action_delete_repo)
        self.menu_users.addAction(self.action_update_user)
        self.menu_users.addAction(self.action_delete_user_from_repo)
        self.menu_users.addSeparator()
        self.menu_users.addAction(self.action_switch_user)
        self.menu_file.addAction(self.menu_repo.menuAction())
        self.menu_file.addAction(self.menu_users.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_add_entity.addAction(self.action_add_file)
        self.menu_add_entity.addAction(self.action_add_URL)
        self.menu_mark.addAction(self.action_mark_tag)
        self.menu_mark.addAction(self.action_mark_field)
        self.menu_objects.addAction(self.menu_add_entity.menuAction())
        self.menu_objects.addAction(self.menu_mark.menuAction())
        self.menu_objects.addSeparator()
        self.menu_objects.addAction(self.action_change_entity)
        self.menu_objects.addAction(self.action_delete_entity)
        self.menu_objects.addSeparator()
        self.menu_objects.addSeparator()
        self.menu_objects.addAction(self.action_repo_files)
        self.menu.addAction(self.action_setting_tags)
        self.menu.addAction(self.action_setting_fields)
        self.menu_metadata.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_objects.menuAction())
        self.menubar.addAction(self.menu_metadata.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SmartFiles", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search.setText(QtGui.QApplication.translate("MainWindow", "Найти", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_neural_net.setText(QtGui.QApplication.translate("MainWindow", "включить нейросеть", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "                                               Объекты хранилщиа", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Список объектов хранилища", None, QtGui.QApplication.UnicodeUTF8))
        self.label_entity_browse_tags.setText(QtGui.QApplication.translate("MainWindow", "                                               Объекты хранилщиа", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Отображение тегами", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "                                               Объекты хранилщиа", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Проводник", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_file.setTitle(QtGui.QApplication.translate("MainWindow", "&Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_repo.setTitle(QtGui.QApplication.translate("MainWindow", "&Хранилище", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_users.setTitle(QtGui.QApplication.translate("MainWindow", "&Пользователь", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_objects.setTitle(QtGui.QApplication.translate("MainWindow", "&Объекты", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_add_entity.setTitle(QtGui.QApplication.translate("MainWindow", "&Добавить", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_mark.setTitle(QtGui.QApplication.translate("MainWindow", "&Пометить", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_metadata.setTitle(QtGui.QApplication.translate("MainWindow", "&Метаданные", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "&Управление", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.action_create_repo.setText(QtGui.QApplication.translate("MainWindow", "Создать", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open_repo.setText(QtGui.QApplication.translate("MainWindow", "Открыть", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete_repo.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_update_user.setText(QtGui.QApplication.translate("MainWindow", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete_user_from_repo.setText(QtGui.QApplication.translate("MainWindow", "Удалить из хранилища", None, QtGui.QApplication.UnicodeUTF8))
        self.action_switch_user.setText(QtGui.QApplication.translate("MainWindow", "Переключить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_file.setText(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_URL.setText(QtGui.QApplication.translate("MainWindow", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.action_mark_tag.setText(QtGui.QApplication.translate("MainWindow", "Тегом", None, QtGui.QApplication.UnicodeUTF8))
        self.action_mark_field.setText(QtGui.QApplication.translate("MainWindow", "Полем", None, QtGui.QApplication.UnicodeUTF8))
        self.action_change_entity.setText(QtGui.QApplication.translate("MainWindow", "Изменить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete_entity.setText(QtGui.QApplication.translate("MainWindow", "Удалить", None, QtGui.QApplication.UnicodeUTF8))
        self.action_search.setText(QtGui.QApplication.translate("MainWindow", "Найти", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_files.setText(QtGui.QApplication.translate("MainWindow", "Файлы хранилища", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setting_tags.setText(QtGui.QApplication.translate("MainWindow", "Тегами", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setting_fields.setText(QtGui.QApplication.translate("MainWindow", "Полями", None, QtGui.QApplication.UnicodeUTF8))

